name: immich_mobile
description: Immich - selfhosted backup media file on mobile phone

publish_to: "none"
version: 1.23.0+33

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: ^2.0.6
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  dio: ^4.0.4
  cached_network_image: ^3.2.1
  percent_indicator: ^4.2.2
  intl: ^0.17.0
  auto_route: ^4.0.1
  exif: ^3.1.1
  transparent_image: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
  fluttertoast: ^8.0.8
  video_player: ^2.2.18
  chewie: ^1.2.2
  badges: ^2.0.2
  photo_view: ^0.14.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter_map: ^0.14.0
  flutter_udid: ^2.0.0
  package_info_plus: ^1.4.0
  flutter_spinkit: ^5.1.0
  flutter_swipe_detector: ^2.0.0
  equatable: ^2.0.3
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.3
  http: 0.13.4
  cancellation_token_http: ^1.1.0
  easy_localization: ^3.0.1
  share_plus: ^4.0.10
  flutter_displaymode: ^0.4.0

  path: ^1.8.1
  path_provider: ^2.0.11
  latlong2: ^0.8.1
  collection: ^1.16.0
  http_parser: ^4.0.1

  openapi:
    path: openapi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  auto_route_generator: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
  fonts:
    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans.ttf
        - asset: fonts/WorkSans-Italic.ttf
          style: italic
    - family: SnowburstOne
      fonts:
        - asset: fonts/SnowburstOne.ttf

flutter_icons:
  image_path_android: "assets/immich-logo-no-outline.png"
  image_path_ios: "assets/immich-logo-no-outline.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon

analyzer:
  exclude:
    - openapi/**
