name: immich_mobile
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  photo_manager: ^1.3.10
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.0
  hive:
  hive_flutter:
  dio: ^4.0.4
  device_info_plus: ^3.2.1
  cached_network_image: ^3.2.0
  google_fonts: ^2.2.0
  percent_indicator: ^3.4.0
  intl: ^0.17.0
  auto_route: ^3.2.2
  exif: ^3.1.1
  transparent_image: ^2.0.0
  visibility_detector: ^0.2.2
  flutter_launcher_icons: "^0.9.2"
  fluttertoast: ^8.0.8
  video_player: ^2.2.18
  chewie: ^1.2.2
  sliver_tools: ^0.2.5
  badges: ^2.0.2
  photo_view: ^0.13.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  mapbox_gl: ^0.15.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  auto_route_generator: ^3.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path_android: "assets/immich-logo-no-outline.png"
  image_path_ios: "assets/immich-logo-no-outline.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon
