name: Feature Request
description: Request a feature that you would like for the app
title: "[Feature]: "
labels: ["feature", "need triage"]
assignees:
  - ""

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: feature-detail
    attributes:
      label: Feature detail
      placeholder: Describe the feature you would like to see for the app
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Choose the platform for the feature
      options:
        - Web
        - Mobile App
        - Server
    validations:
      required: true
