version: "3.8"

services:
  immich-server:
    image: immich-server-dev:latest
    build:
      context: ../server
      dockerfile: Dockerfile
    command: npm run start:dev immich
    volumes:
      - ../server:/usr/src/app
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - database

  immich-machine-learning:
    image: immich-machine-learning-dev:latest
    build:
      context: ../machine-learning
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ../machine-learning:/usr/src/app
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - database

  immich-microservices:
    image: immich-microservices:latest
    build:
      context: ../server
      dockerfile: Dockerfile
    command: npm run start:dev microservices
    volumes:
      - ../server:/usr/src/app
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - database
      - immich-server

  immich-web:
    image: immich-web-dev:1.9.0
    build:
      context: ../web
      dockerfile: Dockerfile
      target: dev
    command: npm run dev --host
    env_file:
      - .env
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ../web:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - immich-server

  redis:
    container_name: immich_redis
    image: redis:6.2

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  immich-proxy:
    container_name: immich_proxy
    image: immich-proxy-dev:latest
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - 2283:80
      - 2284:443
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
