version: "3.8"

name: "immich-test-e2e"

services:
  immich-server:
    image: immich-server-dev:latest
    build:
      context: ../server
      dockerfile: Dockerfile
      target: builder
    command: npm run test:e2e
    volumes:
      - ../server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=e2e_test
      - IMMICH_RUN_ALL_TESTS=true
    depends_on:
      - database

  database:
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    command: -c fsync=off
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: e2e_test
    logging:
      driver: none
