version: "3.8"

name: "immich-test-e2e"

services:
  immich-server:
    image: immich-server-dev:latest
    build:
      context: ../
      dockerfile: server/Dockerfile
      target: dev
    command: npm run test:e2e
    volumes:
      - ../server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=e2e_test
      - IMMICH_RUN_ALL_TESTS=true
    depends_on:
      - database

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: e2e_test
    logging:
      driver: none
